In [1]:
import numpy as np

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a[2]

np.int64(2)

In [4]:
a[-1]

np.int64(11)

In [5]:
a[2:4]

array([2, 3])

In [6]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
a[:5]

array([0, 1, 2, 3, 4])

In [8]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

In [9]:
a[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [10]:
a[:4] = [-1, -2, -3, -4]
a

array([-1, -2, -3, -4,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
for x in a:
    print(x, sep=' ', end=' ')

-1 -2 -3 -4 4 5 6 7 8 9 10 11 

In [12]:
x = np.array([(1, 2, 3), (10, 20, 30), (100, 200, 300)])
x

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [13]:
x[1, 1]

np.int64(20)

In [14]:
x[-1, -1]

np.int64(300)

In [15]:
x[2]

array([100, 200, 300])

In [16]:
x[:, 1]

array([  2,  20, 200])

In [17]:
for i in x.flat:
    print(i, end=' : ')

1 : 2 : 3 : 10 : 20 : 30 : 100 : 200 : 300 : 

In [19]:
a = np.arange(1, 82).reshape(3, 3, 3, 3)
a[1, 2, 0, 2]

np.int64(48)

In [20]:
a[:, 1, :, :]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[64, 65, 66],
        [67, 68, 69],
        [70, 71, 72]]])

In [21]:
a[0, 0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a[0, 0, :, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a[0:2, 0:2, 1, 1]

array([[ 5, 14],
       [32, 41]])

In [24]:
a[..., 1, 1]

array([[ 5, 14, 23],
       [32, 41, 50],
       [59, 68, 77]])

In [25]:
a = np.arange(1, 9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a[0]

np.int64(1)

In [27]:
a[[0]]

array([1])

In [28]:
b = a[ [0] ]
b

array([1])

In [29]:
b[0] = 100
b

array([100])

In [30]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
a[ [0,1,5,7] ]

array([1, 2, 6, 8])

In [32]:
a[[0, 0, 1, 1, 1, 2, 3, 4, 5, 6, 7]]

array([1, 1, 2, 2, 2, 3, 4, 5, 6, 7, 8])

In [33]:
a[ [0,1,5,7] ] = [10, 20, 30, 40]
a

array([10, 20,  3,  4,  5, 30,  7, 40])

In [34]:
idx = [0, 0, 1, 1, 2, 3]
a[idx]

array([10, 10, 20, 20,  3,  4])

In [35]:
bidx = [True, True, False, False, False, True, False, False]
a[bidx]

array([10, 20, 30])

In [36]:
a[a>5]

array([10, 20, 30,  7, 40])

In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[ a>5 ]

array([6, 7, 8, 9])

In [39]:
a = np.arange(1, 9)
i = np.array([[0, 1], [2, 3]])
a[i]

array([[1, 2],
       [3, 4]])

In [40]:
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
idx = [2, 1, 0]
a[idx]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [42]:
indx = np.array([[1, 0], [2, 1]])
a[indx]

array([[[ 5,  6,  7,  8],
        [ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [43]:
i0 = [0,1]
i1 = [1,2]
a[i0, i1]

array([2, 7])

In [44]:
a[:, i1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [45]:
a[i0, 1]

array([2, 6])

In [46]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
a[[2, 4, 6]] = [-1, -2, -3]
a

array([ 0,  1, -1,  3, -2,  5, -3])

In [48]:
a[[2, 4, 6]] = 10, 20, 30
a

array([ 0,  1, 10,  3, 20,  5, 30])

In [49]:
a[[0, 1, 2]] += 3
a

array([ 3,  4, 13,  3, 20,  5, 30])