In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3]
a = np.array([1, 2, 3])

In [3]:
lst * 2

[1, 2, 3, 1, 2, 3]

In [4]:
a * 2

array([2, 4, 6])

In [5]:
-a

array([-1, -2, -3])

In [6]:
a - 3

array([-2, -1,  0])

In [7]:
a + 5

array([6, 7, 8])

In [8]:
a * 5

array([ 5, 10, 15])

In [9]:
a / 2

array([0.5, 1. , 1.5])

In [10]:
a // 2

array([0, 1, 1])

In [11]:
a / 5

array([0.2, 0.4, 0.6])

In [12]:
a ** 5

array([  1,  32, 243])

In [13]:
a % 2

array([1, 0, 1])

In [14]:
b = np.array([3, 4, 5])
a - b

array([-2, -2, -2])

In [15]:
a + b

array([4, 6, 8])

In [16]:
a * b

array([ 3,  8, 15])

In [17]:
b / a

array([3.        , 2.        , 1.66666667])

In [18]:
a // b

array([0, 0, 0])

In [19]:
b ** a

array([  3,  16, 125])

In [20]:
b % a

array([0, 0, 2])

In [21]:
b = np.arange(1, 7)
b.resize(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

In [23]:
a = np.arange(1, 19)
a.resize(3, 3, 2)
b = np.ones((3, 2))
a - b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]]])

In [24]:
a * 10

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60]],

       [[ 70,  80],
        [ 90, 100],
        [110, 120]],

       [[130, 140],
        [150, 160],
        [170, 180]]])

In [25]:
a // b

array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.],
        [17., 18.]]])

In [26]:
a = np.array([1,2,6,8])
a

array([1, 2, 6, 8])

In [27]:
a += 5
a

array([ 6,  7, 11, 13])

In [28]:
a + 5

array([11, 12, 16, 18])

In [29]:
a += 5
a

array([11, 12, 16, 18])

In [30]:
a -= 5

In [31]:
a

array([ 6,  7, 11, 13])

In [33]:
b = np.ones(4)
b

array([1., 1., 1., 1.])

In [34]:
b *= a
b

array([ 6.,  7., 11., 13.])