In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 10, 20, 30])
a[a>5]

array([10, 20, 30])

In [3]:
a > 5

array([False, False, False,  True,  True,  True])

In [4]:
b = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a == b

array([ True,  True,  True, False, False, False])

In [6]:
a != b

array([False, False, False,  True,  True,  True])

In [7]:
a > 2

array([False, False,  True,  True,  True,  True])

In [8]:
a > b

array([False, False, False,  True,  True,  True])

In [9]:
np.greater(a, b)

array([False, False, False,  True,  True,  True])

In [10]:
a < b

array([False, False, False, False, False, False])

In [11]:
np.less(a, b)

array([False, False, False, False, False, False])

In [12]:
np.equal(a, b)

array([ True,  True,  True, False, False, False])

In [13]:
np.array_equal(a, b)

False

In [14]:
np.any(a>5)

np.True_

In [15]:
np.any(a == 5)

np.False_

In [16]:
np.all(a > 4)

np.False_

In [17]:
a / 0

C:\Users\User\AppData\Local\Temp\ipykernel_5980\1979898162.py:1: RuntimeWarning: divide by zero encountered in divide
  a / 0


array([inf, inf, inf, inf, inf, inf])

In [19]:
b = np.array([1, 2, np.inf])
b

array([ 1.,  2., inf])

In [20]:
b * 0

C:\Users\User\AppData\Local\Temp\ipykernel_5980\946493483.py:1: RuntimeWarning: invalid value encountered in multiply
  b * 0


array([ 0.,  0., nan])

In [21]:
c = b*0
c

C:\Users\User\AppData\Local\Temp\ipykernel_5980\2563788479.py:1: RuntimeWarning: invalid value encountered in multiply
  c = b*0


array([ 0.,  0., nan])

In [22]:
c.sum()

np.float64(nan)

In [25]:
b = np.array([1, 2, np.nan, np.inf, -np.inf])
b

array([  1.,   2.,  nan,  inf, -inf])

In [26]:
np.isinf(b) 

array([False, False, False,  True,  True])

In [27]:
np.isnan(b)

array([False, False,  True, False, False])

In [28]:
idx = np.isinf(b)
idx

array([False, False, False,  True,  True])

In [29]:
b[~idx]

array([ 1.,  2., nan])

In [30]:
np.isfinite(b)

array([ True,  True, False, False, False])

In [31]:
np.isreal(b)

array([ True,  True,  True,  True,  True])

In [32]:
x = np.array([True, False, True, False])
y = np.array([True, True, False, False])
np.logical_and(x, y)

array([ True, False, False, False])

In [33]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [34]:
np.logical_not(y)

array([False, False,  True,  True])

In [ ]:
np.logical_xor