In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 5])

array([1, 2, 3, 5])

In [3]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
np.empty(10, dtype='int16')

array([ 21120, -30106,    575,      0,      0,      0,      0,      0,
            1,      0], dtype=int16)

In [5]:
np.empty((2, 3), dtype='int16')

array([[ -9728, -30115,    575],
       [     0,      0,      0]], dtype=int16)

In [7]:
np.empty((3, 2), dtype='int8')

array([[120,  46],
       [102, 108],
       [105, 112]], dtype=int8)

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones([3,4], dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [13]:
np.full((2, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [14]:
np.mat('1 2 3 4')

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

In [15]:
np.asmatrix('1 2 3 4')

matrix([[1, 2, 3, 4]])

In [16]:
np.asmatrix('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [17]:
np.asmatrix( [(1,2,3), (4,5,6)])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
np.diag([(1,2,3), (4,5,6), (7,8,9)])

array([1, 5, 9])

In [20]:
np.diagflat([(1,2,3), (4,5,6), (7,8,9)])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [21]:
np.tri(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [22]:
np.tri(4, 2)

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
a = np.array( [(1,2,3), (4,5,6), (7,8,9)] )

In [24]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [26]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [27]:
np.tril([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [1, 2, 0, 0, 0],
       [1, 2, 3, 0, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 5]])

In [28]:
np.tril([[[1,2,3], [4,5,6], [7,8,9]]])

array([[[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]]])

In [29]:
np.vander([1,2,3])

array([[1, 1, 1],
       [4, 2, 1],
       [9, 3, 1]])

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [33]:
np.cos(np.arange(0, np.pi, 0.1))

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [34]:
np.linspace(0, np.pi, 0)

array([], dtype=float64)

In [35]:
np.linspace(0, np.pi, 2)

array([0.        , 3.14159265])

In [36]:
np.linspace(0, np.pi, 5)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [37]:
np.logspace(0, 2, 3)

array([  1.,  10., 100.])

In [38]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [39]:
np.geomspace(1, 4, 3)

array([1., 2., 4.])

In [40]:
np.geomspace(1, 16, 5)

array([ 1.,  2.,  4.,  8., 16.])

In [41]:
a = np.array( [(1, 2), (3, 4)] )

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
b = np.copy(a)

In [44]:
b

array([[1, 2],
       [3, 4]])

In [45]:
b[0] = 100

In [46]:
b

array([[100, 100],
       [  3,   4]])

In [47]:
a

array([[1, 2],
       [3, 4]])

In [48]:
def get_range(x, y):
    return 100*x + y

In [49]:
a = np.fromfunction(get_range, (2, 2))

In [50]:
a

array([[  0.,   1.],
       [100., 101.]])

In [51]:
np.fromfunction(lambda x, y: x*100+y, (2, 2))

array([[  0.,   1.],
       [100., 101.]])

In [52]:
np.fromiter("hello", dtype='U1')

array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

In [53]:
def get_range(N):
    for i in range(N):
        yield i
 
a = np.fromiter(get_range(4), dtype='int8')

In [54]:
a

array([0, 1, 2, 3], dtype=int8)

In [55]:
np.fromstring('1 2 3', dtype='int16', sep= ' ')

array([1, 2, 3], dtype=int16)