In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1, 2, "3", True])

In [6]:
b

array(['1', '2', '3', 'True'], dtype='<U21')

In [8]:
a[0], a[2]

(np.int64(1), np.int64(3))

In [9]:
b[0]

np.str_('1')

In [10]:
b[1] = '123'

In [11]:
b

array(['1', '123', '3', 'True'], dtype='<U21')

In [12]:
b[1] = 1234

In [13]:
b

array(['1', '1234', '3', 'True'], dtype='<U21')

In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a[3]

np.int64(4)

In [16]:
a[ [1,1,1,1,1,1,1] ]

array([2, 2, 2, 2, 2, 2, 2])

In [17]:
a[ [True, True, False, False, False, False, True, True, True] ]

array([1, 2, 7, 8, 9])

In [19]:
b = a.reshape(3, 3)

In [20]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
b[1,2]

np.int64(6)