In [1]:
import numpy as np

In [2]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [3]:
a.shape

(9,)

In [4]:
a.dtype

dtype('float64')

In [5]:
a.dtype = 'int8'
a

array([-102, -103, -103, -103, -103, -103,  -71,   63, -102, -103, -103,
       -103, -103, -103,  -55,   63,   51,   51,   51,   51,   51,   51,
        -45,   63, -102, -103, -103, -103, -103, -103,  -39,   63,    0,
          0,    0,    0,    0,    0,  -32,   63,   51,   51,   51,   51,
         51,   51,  -29,   63,  102,  102,  102,  102,  102,  102,  -26,
         63, -102, -103, -103, -103, -103, -103,  -23,   63,  -51,  -52,
        -52,  -52,  -52,  -52,  -20,   63], dtype=int8)

In [6]:
a.size

72

In [8]:
a.dtype = np.float64
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [9]:
a.dtype = np.float32
a

array([-1.58818684e-23,  1.44999993e+00, -1.58818684e-23,  1.57499993e+00,
        4.17232506e-08,  1.64999998e+00, -1.58818684e-23,  1.69999993e+00,
        0.00000000e+00,  1.75000000e+00,  4.17232506e-08,  1.77499998e+00,
        2.72008302e+23,  1.79999995e+00, -1.58818684e-23,  1.82499993e+00,
       -1.07374184e+08,  1.84999990e+00], dtype=float32)

In [10]:
a.size

18

In [11]:
a.itemsize

4

In [12]:
a.dtype = np.float64
a.size * a.itemsize

72

In [13]:
b = np.ones( (3, 4, 5) )
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [14]:
b.ndim

3

In [15]:
b.shape

(3, 4, 5)

In [22]:
b = np.ones( (3, 4, 5) )
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
b.shape = 60
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
b.shape = 12, 5
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
c = b.reshape(3, 2, 10)
c

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [26]:
b[0, 0] = 10
b

array([[10.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [27]:
c

array([[[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

In [28]:
print( id(c), id(b) )

2204849476240 2204860233936


In [29]:
d = b.T
d

array([[10.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [30]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a
a.shape = 3, 3
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.view()
a.shape = 3, 3
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.array([1,2,3,4,5,6,7,8])
b = a.copy()
a[0] = 100
a

array([100,   2,   3,   4,   5,   6,   7,   8])

In [34]:
b

array([1, 2, 3, 4, 5, 6, 7, 8])