In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.shape = 2, 5
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b = a.reshape(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b[0] = -111
b

array([-111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [6]:
a

array([[-111,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [8]:
b = a.reshape(9)

ValueError: cannot reshape array of size 10 into shape (9,)

In [9]:
a.shape = -1, 2
a

array([[-111,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9]])

In [10]:
a.shape = -1, 5
a

array([[-111,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [11]:
b

array([-111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [12]:
b.reshape(-1, 1)
b

array([-111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [13]:
b.reshape(-1, 1)

array([[-111],
       [   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [   7],
       [   8],
       [   9]])

In [14]:
b.reshape(1, -1)

array([[-111,    1,    2,    3,    4,    5,    6,    7,    8,    9]])

In [15]:
a

array([[-111,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [16]:
a.ravel()

array([-111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [17]:
a.shape = -1
a

array([-111,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [18]:
a.resize(2, 5)
a

array([[-111,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [19]:
a.resize(3, 3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [21]:
a.resize(3, 3, refcheck=False)
a

array([[-111,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8]])

In [22]:
a.resize(4, 5, refcheck=False)
a

array([[-111,    1,    2,    3,    4],
       [   5,    6,    7,    8,    0],
       [   0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0]])

In [23]:
a[0, 0] = -1
a

array([[-1,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [24]:
a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
a

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [25]:
b = a.T
b

array([[ 1,  1,  1],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [26]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x.shape = 1, -1
x

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
x.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:
test = np.arange(32).reshape(8, 2, 2)
test

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [31]:
test.shape

(8, 2, 2)

In [32]:
test4 = np.expand_dims(test, axis=0)
test4.shape

(1, 8, 2, 2)

In [35]:
test4[0,0,0,0] = -5
test

array([[[-5,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [36]:
test4.shape

(1, 8, 2, 2)

In [38]:
a = np.append(test4, test4, axis=0)
a.shape

(2, 8, 2, 2)

In [39]:
b = np.delete(a, 0, axis=0)
b.shape

(1, 8, 2, 2)

In [40]:
b = np.expand_dims(test4, axis=-1)
b.shape

(1, 8, 2, 2, 1)

In [41]:
c = np.squeeze(b)
c.shape

(8, 2, 2)

In [42]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [44]:
b.shape

(1, 9)

In [ ]:
b = a[:, np.new