In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4], 'float64')

In [5]:
a

array([1., 2., 3., 4.])

In [6]:
np.sctypeDict

{'bool': numpy.bool,
 'float16': numpy.float16,
 'float32': numpy.float32,
 'float64': numpy.float64,
 'longdouble': numpy.longdouble,
 'complex64': numpy.complex64,
 'complex128': numpy.complex128,
 'clongdouble': numpy.clongdouble,
 'bytes_': numpy.bytes_,
 'str_': numpy.str_,
 'void': numpy.void,
 'object_': numpy.object_,
 'datetime64': numpy.datetime64,
 'timedelta64': numpy.timedelta64,
 'int8': numpy.int8,
 'byte': numpy.int8,
 'uint8': numpy.uint8,
 'ubyte': numpy.uint8,
 'int16': numpy.int16,
 'short': numpy.int16,
 'uint16': numpy.uint16,
 'ushort': numpy.uint16,
 'intc': numpy.intc,
 'uintc': numpy.uintc,
 'int32': numpy.int32,
 'long': numpy.int32,
 'uint32': numpy.uint32,
 'ulong': numpy.uint32,
 'int64': numpy.int64,
 'longlong': numpy.int64,
 'uint64': numpy.uint64,
 'ulonglong': numpy.uint64,
 'intp': numpy.int64,
 'uintp': numpy.uint64,
 'double': numpy.float64,
 'cdouble': numpy.complex128,
 'single': numpy.float32,
 'csingle': numpy.complex64,
 'half': numpy.float16,

In [7]:
a = np.array([1,2,3,4], 'str_')

In [8]:
a

array(['1', '2', '3', '4'], dtype='<U1')

In [9]:
np.complex64(10)

np.complex64(10+0j)

In [10]:
np.int16(10.5)

np.int16(10)

In [11]:
a = np.array([1, 2, 5000, 1000], dtype='int8')

OverflowError: Python integer 5000 out of bounds for int8

In [12]:
a

array(['1', '2', '3', '4'], dtype='<U1')

In [13]:
a = np.array([1, 2, 5000, 1000], dtype='int32')

In [14]:
a

array([   1,    2, 5000, 1000], dtype=int32)

In [15]:
np.complex64(a)

array([1.e+00+0.j, 2.e+00+0.j, 5.e+03+0.j, 1.e+03+0.j], dtype=complex64)

In [16]:
b = np.complex64(a)

In [17]:
c = np.int32(b)

C:\Users\User\AppData\Local\Temp\ipykernel_4964\4084964917.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  c = np.int32(b)


In [18]:
c

array([   1,    2, 5000, 1000], dtype=int32)

In [19]:
np.array( (1,2,3) )

array([1, 2, 3])

In [20]:
np.array( 'Hello' )

array('Hello', dtype='<U5')

In [21]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [22]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a = np.array([[1, 2], [3, 4], [5, 6, 7]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [24]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [25]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
b[0]

array([[1, 2],
       [3, 4]])

In [27]:
b[1]

array([[5, 6],
       [7, 8]])

In [28]:
b[2]

array([[ 9, 10],
       [11, 12]])

In [29]:
b[0, 0]

array([1, 2])

In [ ]:
b[