In [1]:
import numpy as np

In [3]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6],
       [7, 8]])

In [5]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [6]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
np.hstack([a,b, a])

array([[1, 2, 5, 6, 1, 2],
       [3, 4, 7, 8, 3, 4]])

In [10]:
a = np.fromiter(range(18), dtype='int32')
b = np.fromiter(range(18, 36), dtype='int32')
a.resize(3, 3, 2)
b.resize(3, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]], dtype=int32)

In [11]:
b

array([[[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]], dtype=int32)

In [12]:
c = np.hstack([a, b])
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [30, 31],
        [32, 33],
        [34, 35]]], dtype=int32)

In [13]:
c.shape

(3, 6, 2)

In [14]:
d = np.vstack([a, b])
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]], dtype=int32)

In [15]:
d.shape

(6, 3, 2)

In [16]:
a = np.fromstring('1 2 3 4', sep = ' ')
b = np.fromstring('5 6 7 8', sep = ' ')
np.hstack([a, b])

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [17]:
np.vstack([a, b])

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [18]:
np.column_stack([a,b])

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 8.]])

In [19]:
a = np.arange(1, 13)
b = np.arange(13, 26)
a.resize(3, 3, 2)
b.resize(3, 3, 2)

c0 = np.concatenate([a, b], axis=0) # размерность 6x3x2
c1 = np.concatenate([a, b], axis=1) # размерность 3x6x2
c2 = np.concatenate([a, b], axis=2) # размерность 3x3x4

In [20]:
c0.shape

(6, 3, 2)

In [21]:
np.r_[[1, 2, 3], 4, 5]

array([1, 2, 3, 4, 5])

In [22]:
np.r_[1:9, 90, 100]

array([  1,   2,   3,   4,   5,   6,   7,   8,  90, 100])

In [23]:
np.r_[ np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [24]:
np.r_[ [(1,2,3), (4,5,6)], [(7,8,9)] ] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

In [26]:
np.c_[ [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
np.c_[ [(1,2,3), (4,5,6)], [[7],[8]] ]

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [28]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [30]:
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [32]:
a.shape = 10, -1
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [33]:
np.vsplit(a, 2)

[array([[0],
        [1],
        [2],
        [3],
        [4]]),
 array([[5],
        [6],
        [7],
        [8],
        [9]])]

In [34]:
a = np.arange(12)
a.resize(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [35]:
np.hsplit(a, 2)

[array([[0, 1, 2],
        [6, 7, 8]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11]])]

In [36]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]

In [37]:
a = np.arange(18)
a.resize(3, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [39]:
np.array_split(a, 2, axis=2)

[array([[[ 0],
         [ 2],
         [ 4]],
 
        [[ 6],
         [ 8],
         [10]],
 
        [[12],
         [14],
         [16]]]),
 array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]],
 
        [[13],
         [15],
         [17]]])]

In [40]:
np.array_split(a, 2, axis=0)

[array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 array([[[12, 13],
         [14, 15],
         [16, 17]]])]

In [41]:
np.array_split(a, 2, axis=1)

[array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 6,  7],
         [ 8,  9]],
 
        [[12, 13],
         [14, 15]]]),
 array([[[ 4,  5]],
 
        [[10, 11]],
 
        [[16, 17]]])]