In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 4, 3, 2, 1])
a

array([1, 2, 3, 4, 4, 3, 2, 1])

In [5]:
set1 = np.unique(a)
set1

array([1, 2, 3, 4])

In [6]:
np.unique(a, return_counts=True)

(array([1, 2, 3, 4]), array([2, 2, 2, 2]))

In [7]:
np.unique(a, return_index=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 3]))

In [8]:
np.unique(a, return_inverse=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 3, 3, 2, 1, 0]))

In [9]:
set1, idx = np.unique(a, return_inverse=True)

In [10]:
set1

array([1, 2, 3, 4])

In [11]:
idx

array([0, 1, 2, 3, 3, 2, 1, 0])

In [12]:
set1[idx]

array([1, 2, 3, 4, 4, 3, 2, 1])

In [13]:
x = np.array([[0, 1, 1, 2],[0, 1, 1, 2],[9, 1, 1, 2]])
x

array([[0, 1, 1, 2],
       [0, 1, 1, 2],
       [9, 1, 1, 2]])

In [14]:
np.unique(x)

array([0, 1, 2, 9])

In [15]:
np.unique(x, axis=0)

array([[0, 1, 1, 2],
       [9, 1, 1, 2]])

In [16]:
np.unique(x, axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [9, 1, 2]])

In [17]:
x = np.array([0, 1, 2, 3])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.in1d(x, y)

C:\Users\User\AppData\Local\Temp\ipykernel_11400\2268951300.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(x, y)


array([False,  True,  True,  True])

In [18]:
np.isin(x, y)

array([False,  True,  True,  True])

In [19]:
np.intersect1d(x, y)

array([1, 2, 3])

In [20]:
np.union1d(x, y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.setdiff1d(x, y)

array([0])