In [1]:
import numpy as np

In [5]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)


In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
a*b

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [7]:
np.dot(a, b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [8]:
np.dot(b, a)

array([[138, 171, 204],
       [174, 216, 258],
       [210, 261, 312]])

In [9]:
np.matmul(b,a )

array([[138, 171, 204],
       [174, 216, 258],
       [210, 261, 312]])

In [10]:
a = np.arange(1, 10)
b = np.ones(9)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.dot(a, b)

np.float64(45.0)

In [13]:
np.inner(a, b)

np.float64(45.0)

In [14]:
np.outer(a, b)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [15]:
a @ b

np.float64(45.0)

In [17]:
a.resize(3, 3)
b.resize(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a @ b

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

In [20]:
b @ a

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]])

In [21]:
a = np.array([1,2,3])
b = np.arange(4,10).reshape(3,2)
a

array([1, 2, 3])

In [22]:
b

array([[4, 5],
       [6, 7],
       [8, 9]])

In [23]:
np.dot(a, b)

array([40, 46])

In [24]:
a = np.array([1, 2])
a

array([1, 2])

In [25]:
np.dot(b, a)

array([14, 20, 26])

In [26]:
a.shape = -1, 1
a

array([[1],
       [2]])

In [27]:
np.dot(b, a)

array([[14],
       [20],
       [26]])

In [28]:
b @ a

array([[14],
       [20],
       [26]])

In [29]:
a = np.array([(1, 2, 3), (1, 4, 9), (1, 8, 27)])
a

array([[ 1,  2,  3],
       [ 1,  4,  9],
       [ 1,  8, 27]])

In [30]:
np.linalg.matrix_rank(a)

np.int64(3)

In [31]:
y = np.array([10, 20, 30])
np.linalg.solve(a, y)

array([-5.        , 10.        , -1.66666667])

In [32]:
inva = np.linalg.inv(a)
inva

array([[ 3.        , -2.5       ,  0.5       ],
       [-1.5       ,  2.        , -0.5       ],
       [ 0.33333333, -0.5       ,  0.16666667]])

In [33]:
inva @ y

array([-5.        , 10.        , -1.66666667])