In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 10, 20, 30])
b = np.array([2])
a * b

array([ 2,  4,  6, 20, 40, 60])

In [3]:
a + b

array([ 3,  4,  5, 12, 22, 32])

In [4]:
b = np.array([2, 3])
a + b

ValueError: operands could not be broadcast together with shapes (6,) (2,) 

In [5]:
b = np.array([2, 3, 4])
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a + b

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [7]:
a = np.arange(6).reshape(3, 1, 2)
b = np.ones(4).reshape(2, 2)
a

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [8]:
b

array([[1., 1.],
       [1., 1.]])

In [9]:
c = a * b
c

array([[[0., 1.],
        [0., 1.]],

       [[2., 3.],
        [2., 3.]],

       [[4., 5.],
        [4., 5.]]])

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])

In [11]:
a * b + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
a.shape = 1, 1, -1
b.shape = 1, -1, 1
c.shape = -1, 1, 1
d = a * b + c

In [13]:
d

array([[[11, 15, 19],
        [12, 17, 22]],

       [[12, 16, 20],
        [13, 18, 23]],

       [[13, 17, 21],
        [14, 19, 24]],

       [[14, 18, 22],
        [15, 20, 25]]])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([7, 8, 9, 10])
an, bn, cn = np.ix_(a, b, c)
an

array([[[1]],

       [[2]],

       [[3]]])

In [17]:
bn

array([[[4],
        [5]]])

In [18]:
cn

array([[[ 7,  8,  9, 10]]])