In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 10, 20, 30])

In [3]:
a.sum()

np.int64(66)

In [4]:
a.max()

np.int64(30)

In [5]:
a.min()

np.int64(1)

In [6]:
a.mean()

np.float64(11.0)

In [7]:
a.resize(3, 2)
a

array([[ 1,  2],
       [ 3, 10],
       [20, 30]])

In [8]:
a.sum()

np.int64(66)

In [9]:
a.sum(axis=0)

array([24, 42])

In [10]:
a.sum(axis=1)

array([ 3, 13, 50])

In [11]:
a.max(axis=0)

array([20, 30])

In [12]:
a = np.array([-1, 1, 5, -44, 32, 2])
np.abs(a)

array([ 1,  1,  5, 44, 32,  2])

In [13]:
np.amax(a)

np.int64(32)

In [14]:
np.amin(a)

np.int64(-44)

In [15]:
np.round(0.333)

np.float64(0.0)

In [16]:
np.round(0.633)

np.float64(1.0)

In [17]:
np.argmax(a)

np.int64(4)

In [18]:
a.resize(2, 3)
a

array([[ -1,   1,   5],
       [-44,  32,   2]])

In [19]:
np.amax(a, axis=0)

array([-1, 32,  5])

In [20]:
np.amax(a, axis=1)

array([ 5, 32])

In [21]:
a = np.linspace(0, np.pi, 10)
a

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [22]:
np.sin(a)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])

In [23]:
np.random.rand()

0.35568817144913634

In [24]:
np.random.rand(5)

array([0.90065307, 0.09168516, 0.12638894, 0.52679574, 0.2496607 ])

In [25]:
np.random.rand(3, 5)

array([[0.07452223, 0.5034393 , 0.07111112, 0.64047811, 0.75921992],
       [0.52500217, 0.66308161, 0.2374174 , 0.31999092, 0.4596446 ],
       [0.2085569 , 0.90317468, 0.51597858, 0.62454881, 0.21239277]])

In [26]:
np.random.randint(10), np.random.randint(10), np.random.randint(10), np.random.randint(10)

(5, 0, 6, 1)

In [27]:
np.random.randint(1, 11)

6

In [28]:
np.random.randint(5, size=7)

array([1, 1, 2, 4, 3, 3, 1], dtype=int32)

In [29]:
np.random.randint(1, 11, size=(3, 4))

array([[ 4,  1,  1,  8],
       [10,  2,  9,  2],
       [ 1,  6,  1,  3]], dtype=int32)

In [30]:
np.random.randn()

-0.03459081847678276

In [31]:
np.random.seed(13)
np.random.randint(10, size=10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2], dtype=int32)

In [32]:
np.random.randint(10, size=10)

array([6, 5, 9, 4, 2, 0, 3, 5, 3, 6], dtype=int32)

In [33]:
np.random.seed(13)
np.random.randint(10, size=10)

array([2, 0, 0, 6, 2, 4, 9, 3, 4, 2], dtype=int32)

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.random.shuffle(a)
a

array([7, 4, 9, 0, 3, 1, 2, 8, 5, 6])

In [36]:
np.random.permutation(11)

array([ 4,  0,  2,  1,  7,  9,  6,  8, 10,  5,  3], dtype=int32)